### ISSUE TITLE
Todos

### ISSUE THREAD

**Issue by EliphazBouye** [EliphazBouye/nestjs-task-api#1]
# Todos

- [x] Task service error handling throught exception
- [x] Task data validation
- [x] Task Controller unit tests
- [ ] Task Service unit tests
- [ ] User authentification
- [ ] Route protection and authorization
- [ ] User forget, reset password
- [ ] Update profile info 
- [x] Controller unit tests
- [ ] Auth service unit test
- [ ] Auth controller unit test
- [ ] User service unit test
- [ ] User controller unit test
